from invocation import Invocation

all_invocations = {
    "Try Again": Invocation("Try Again", "Players have ten attempts to complete a raid.", 5, "Attempts"),
    "Persistence": Invocation("Persistence", "Players have five attempts to complete a raid.", 10, "Attempts"),
    "Softcore Run": Invocation("Softcore Run", "Players have three attempts to complete a raid.", 15, "Attempts"),
    "Hardcore Run": Invocation("Hardcore Run", "Players have one attempt to complete a raid.", 25, "Attempts"),
    "Walk for It": Invocation("Walk for It", "Players have 40 minutes to complete the raid, including time spent between each Path.", 10, "Time Limit"),
    "Jog for It": Invocation("Jog for It", "Players have 35 minutes to complete the raid.", 15, "Time Limit"),
    "Run for It": Invocation("Run for It", "Players have 30 minutes to complete the raid.", 20, "Time Limit"),
    "Sprint for It": Invocation("Sprint for It", "Players have 25 minutes to complete the raid.", 25, "Time Limit"),
    "Need Some Help?": Invocation("Need Some Help?", "The quantity of items offered by the Helpful Spirit will be reduced to 66%, with a minimum of one supply of that type.", 15, "Helpful Spirit"),
    "Need Less Help?": Invocation("Need Less Help?", "The quantity of items offered by the Helpful Spirit will be reduced to 33%, with a minimum of one supply of that type.", 25, "Helpful Spirit"),
    "No Help Needed": Invocation("No Help Needed", "The quantity of items offered by the helpful spirit will be reduced to 10%, with a minimum of one supply of that type.", 40, "Helpful Spirit"),
    "Walk the Path": Invocation("Walk the Path", "Completing a path during the raid will cause other paths to level up.", 50, "Paths"),
    "Pathseeker": Invocation("Pathseeker", "All paths will level up once upon entering the raid.", 15, "Path Level"),
    "Pathfinder": Invocation("Pathfinder", "All paths will level up twice upon entering the raid.", 40, "Path Level"),
    "Pathmaster": Invocation("Pathmaster", "All paths will level up three times upon entering the raid.", 50, "Path Level"),
    "Quiet Prayers": Invocation("Quiet Prayers", "Protection prayers will be 10% less effective within the raid.", 20, "Prayer"),
    "Deadly Prayers": Invocation("Deadly Prayers", "Prayer is drained by 20% of damage taken.", 20, "Prayer"),
    "On a Diet": Invocation("On a Diet", "Players can no longer eat food within the raid, though potions that restore health (such as Saradomin brews) can still be used.", 15, "Restoration"),
    "Dehydration": Invocation("Dehydration", "Players can no longer drink potions that restore health.", 30, "Restoration"),
    "Overly Draining": Invocation("Overly Draining", "All special attacks use 100% special attack energy.", 15, "Restoration"),
    "Lively Larvae": Invocation("Lively Larvae", "The number of dark brown eggs launched during Kephri's Mass Incubation attack will increase from 2 to 4.", 5, "Kephri"),
    "More Overlords": Invocation("More Overlords", "An additional scarab is summoned during Kephri's shield healing phases.", 15, "Kephri"),
    "Blowing Mud": Invocation("Blowing Mud", "The number of players targeted by Kephri's Dung Strike attack is increased to two.", 10, "Kephri"),
    "Medic!": Invocation("Medic!", "Kephri will summon scarab swarms outside her shield healing phases. These swarms move 50% slower.", 15, "Kephri"),
    "Aerial Assault": Invocation("Aerial Assault", "Kephri's auto-attack will do more damage, and its attack range will increase from a single tile to a 3x3 area.", 10, "Kephri"),
    "Not Just a Head": Invocation("Not Just a Head", "Zebak will occasionally cast a form of Blood Blitz on all players.", 15, "Zebak"),
    "Arterial Spray": Invocation("Arterial Spray", "Zebak's blood magic will have increased range and healing.", 10, "Zebak"),
    "Blood Thinners": Invocation("Blood Thinners", "Three Blood Clouds are summoned instead of one.", 5, "Zebak"),
    "Upset Stomach": Invocation("Upset Stomach", "Zebak's acid pools will have their spread increased from 3x3 to 5x5 and the jugs will have their water reduced from 5x5 to 3x3.", 15, "Zebak"),
    "Double Trouble": Invocation("Double Trouble", "Akkha will perform two special attacks at once.", 20, "Akkha"),
    "Keep Back": Invocation("Keep Back", "Akkha's will use melee alongside his ranged and magic attacks, which lands just before the projectile attack with no animation.", 10, "Akkha"),
    "Stay Vigilant": Invocation("Stay Vigilant", "Akkha will randomly swap between attack styles and protection prayers rather than at set intervals.", 15, "Akkha"),
    "Feeling Special?": Invocation("Feeling Special?", "Akkha's Detonate attack will trigger in more directions. This is not applied in solo encounters. The Memory Blast attack will only provide two ticks for players to move between safe quadrants. The Trailing Orbs attack spawns an additional orb in front of the player.", 20, "Akkha"),
    "Mind the Gap!": Invocation("Mind the Gap!", "When Ba-Ba knocks back the player to the bottom of the room at 66% and 33% health, players will fall into the pit and die, unless they stand at the northern/southern sides of the room.", 10, "Ba-Ba"),
    "Gotta Have Faith": Invocation("Gotta Have Faith", "Energy blasts from open sarcophagi in Ba-Ba's room will deal additional damage based on the player's remaining prayer points.", 10, "Ba-Ba"),
    "Jungle Japes": Invocation("Jungle Japes", "Ba-Ba's baboons will drop a banana peel on the floor on death. If stepped on, players take a small amount of damage and are stunned for 3 seconds.", 5, "Ba-Ba"),
    "Shaking Things Up": Invocation("Shaking Things Up", "The shockwave from Ba-Ba's slam attack will damage from a 3x3 (+1 tile to the north/west/east/south) to 5x5 (+1 tile to the north/west/east/south).", 10, "Ba-Ba"),
    "Boulderdash": Invocation("Boulderdash", "Ba-Ba's rolling boulders spawn twice as fast.", 10, "Ba-Ba"),
    "Ancient Haste": Invocation("Ancient Haste", "During the first phase of the Wardens' fight, the Wardens will charge at a faster rate.", 10, "The Wardens"),
    "Acceleration": Invocation("Acceleration", "During the second phase of the Wardens' fight, the Warden attacks faster while the obelisk charges faster.", 10, "The Wardens"),
    "Penetration": Invocation("Penetration", "During the second phase of the Wardens' fight, the obelisk will deal more damage to successful attacks and also temporarily disable overhead prayers.", 10, "The Wardens"),
    "Overclocked": Invocation("Overclocked", "During the final phase of the Wardens' fight, the slam attack is performed 1 tick faster.", 10, "The Wardens"),
    "Overclocked 2": Invocation("Overclocked 2", "During the final phase of the Wardens' fight, the slam attack is performed 2 ticks faster.", 10, "The Wardens"),
    "Insanity": Invocation("Insanity", "During the final phase of the Wardens' fight, the following are applied: The slam attack is performed 3 ticks faster. There is less time to reverse the Energy Siphons. The slam attack resumes based on where the Warden left off prior to launching Energy Siphons rather than resetting positions. During enrage phase: Red lightning strikes faster. Tiles are ripped faster. Phantom bosses attack faster.", 50, "The Wardens"),
}